### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by iwanPlays** [robwil/When-will-this-be-over-#1]
It seems to be doing nothing.

![f](https://user-images.githubusercontent.com/25465450/35802717-5f5c1772-0a71-11e8-9684-79cceaa3bb6d.png)

**Comment by robwil** [comment]
I haven't tested this in a while, it's very possible the new versions of VLC have breaking changes. I'll check it out in the next couple of days and make any fixes necessary.

**Comment by robwil** [comment]
![image](https://user-images.githubusercontent.com/605546/35867958-306bcdd2-0b29-11e8-9d65-ed1ef7b5a531.png)
On Mac, the extension shows up in the Extensions menu, and when I click on it, does in fact show the expected display. Also, make sure you are currently playing a video (I notice in your screenshot no video is currently playing), otherwise it will not do anything.

Let me know if this helps.

**Comment by iwanPlays** [comment]
Thank you. I was playing back audio files. I just tested audio files with thumbnails - they also do not work unfortunately. I can confirm it works with video. 

![image](https://user-images.githubusercontent.com/25465450/35870979-59305154-0b63-11e8-8ef4-a8f3033f6bfb.png)

I actually thought this would display the total time of the playlist but I guess I could make the modifications.

Now I just need to find an extension that shows how to add text to the playlist UI...
